In [1]:
import pandas as pd

In [2]:
OD = pd.read_csv('olist_orders_dataset.csv')
ODI = pd.read_csv('olist_order_items_dataset.csv')
OG = pd.read_csv('olist_geolocation_dataset.csv')
OC = pd.read_csv('olist_customers_dataset.csv')

In [3]:
OC

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [4]:
OD

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [5]:
ODI

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [6]:
OG

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [7]:
O = OC[['customer_id','customer_zip_code_prefix','customer_city','customer_state']]

In [8]:
O

,customer_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,13056,campinas,SP
...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,6703,cotia,SP

In [9]:
O = O.merge(OD, on='customer_id',how='inner')

In [10]:
O

,customer_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,06b8999e2fba1a1fbc88172c00ba8bc7,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00
1,18955e83d337fd6b2def6b18a428ac77,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06 00:00:00
2,4e7b3e00288586ebd08712fdd0374a03,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13 00:00:00
3,b2b6027bc5c5109e529d4dc6358b12c3,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10 00:00:00
4,4f2d8ab171c80ec8364f7c12e35b23ad,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,2018-04-13 20:06:37,2018-04-25 00:00:00
99437,e7b71a9017aa05c9a7fd292d714858e8,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,2018-04-11 18:54:45,2018-04-20 00:00:00
99438,5e28dfe12db7fb50a4b2f691faecea5e,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,2018-05-09 19:03:15,2018-05-02 00:00:00
99439,56b18e2166679b8a959d72dd06da27f9,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,2017-11-16 19:58:39,2017-12-05 00:00:00
99440,274fa6071e5e17fe303b9748641082c8,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,2017-12-19 18:50:39,2017-12-21 19:17:21,2017-12-26 18:42:36,2018-01-08 00:00:00

In [11]:
O = O.merge(ODI, on='order_id',how='inner')

In [13]:
O.dropna()

,customer_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00,1,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,2017-05-22 15:22:12,124.99,21.88
1,18955e83d337fd6b2def6b18a428ac77,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06 00:00:00,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-01-18 20:58:32,289.00,46.48
2,4e7b3e00288586ebd08712fdd0374a03,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13 00:00:00,1,bd07b66896d6f1494f5b86251848ced7,7c67e1448b00f6e969d365cea6b010ab,2018-06-05 16:19:10,139.94,17.79
3,b2b6027bc5c5109e529d4dc6358b12c3,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10 00:00:00,1,a5647c44af977b148e0a3a4751a09e2e,7c67e1448b00f6e969d365cea6b010ab,2018-03-27 16:31:16,149.94,23.36
4,4f2d8ab171c80ec8364f7c12e35b23ad,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15 00:00:00,1,9391a573abe00141c56e38d84d7d5b3b,4a3ca9315b744ce9f8e9374361493884,2018-07-31 10:10:09,230.00,22.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,17ddf5dd5d51696bb3d7c6291687be6f,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,2018-04-13 20:06:37,2018-04-25 00:00:00,1,ccb4503d9d43d245d3b295d0544f988b,527801b552d0077ffd170872eb49683b,2018-04-12 16:08:45,74.90,13.88
112646,e7b71a9017aa05c9a7fd292d714858e8,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,2018-04-11 18:54:45,2018-04-20 00:00:00,1,9ede6b0570a75a4b9de4f383329f99ee,3fd1e727ba94cfe122d165e176ce7967,2018-04-10 08:35:12,114.90,14.16
112647,5e28dfe12db7fb50a4b2f691faecea5e,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,2018-05-09 19:03:15,2018-05-02 00:00:00,1,7a5d2e1e131a860ae7d18f6fffa9d689,d9e7e7778b32987280a6f2cb9a39c57d,2018-04-12 20:30:03,37.00,19.04
112648,56b18e2166679b8a959d72dd06da27f9,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,2017-11-16 19:58:39,2017-12-05 00:00:00,1,f819f0c84a64f02d3a5606ca95edd272,4869f7a5dfa277a7dca6462dcf3b52b2,2017-11-09 21:15:51,689.00,22.07
112649,274fa6071e5e17fe303b9748641082c8,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,2017-12-19 18:50:39,2017-12-21 19:17:21,2017-12-26 18:42:36,2018-01-08 00:00:00,1,017692475c1c954ff597feda05131d73,3c7c4a49ec3c6550809089c6a2ca9370,2017-12-26 18:50:39,13.99,7.78

In [14]:
O

,customer_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00,1,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,2017-05-22 15:22:12,124.99,21.88
1,18955e83d337fd6b2def6b18a428ac77,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06 00:00:00,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-01-18 20:58:32,289.00,46.48
2,4e7b3e00288586ebd08712fdd0374a03,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13 00:00:00,1,bd07b66896d6f1494f5b86251848ced7,7c67e1448b00f6e969d365cea6b010ab,2018-06-05 16:19:10,139.94,17.79
3,b2b6027bc5c5109e529d4dc6358b12c3,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10 00:00:00,1,a5647c44af977b148e0a3a4751a09e2e,7c67e1448b00f6e969d365cea6b010ab,2018-03-27 16:31:16,149.94,23.36
4,4f2d8ab171c80ec8364f7c12e35b23ad,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15 00:00:00,1,9391a573abe00141c56e38d84d7d5b3b,4a3ca9315b744ce9f8e9374361493884,2018-07-31 10:10:09,230.00,22.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,17ddf5dd5d51696bb3d7c6291687be6f,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,2018-04-13 20:06:37,2018-04-25 00:00:00,1,ccb4503d9d43d245d3b295d0544f988b,527801b552d0077ffd170872eb49683b,2018-04-12 16:08:45,74.90,13.88
112646,e7b71a9017aa05c9a7fd292d714858e8,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,2018-04-11 18:54:45,2018-04-20 00:00:00,1,9ede6b0570a75a4b9de4f383329f99ee,3fd1e727ba94cfe122d165e176ce7967,2018-04-10 08:35:12,114.90,14.16
112647,5e28dfe12db7fb50a4b2f691faecea5e,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,2018-05-09 19:03:15,2018-05-02 00:00:00,1,7a5d2e1e131a860ae7d18f6fffa9d689,d9e7e7778b32987280a6f2cb9a39c57d,2018-04-12 20:30:03,37.00,19.04
112648,56b18e2166679b8a959d72dd06da27f9,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,2017-11-16 19:58:39,2017-12-05 00:00:00,1,f819f0c84a64f02d3a5606ca95edd272,4869f7a5dfa277a7dca6462dcf3b52b2,2017-11-09 21:15:51,689.00,22.07
112649,274fa6071e5e17fe303b9748641082c8,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,2017-12-19 18:50:39,2017-12-21 19:17:21,2017-12-26 18:42:36,2018-01-08 00:00:00,1,017692475c1c954ff597feda05131d73,3c7c4a49ec3c6550809089c6a2ca9370,2017-12-26 18:50:39,13.99,7.78

In [15]:
OT = O.merge(OG,left_on='customer_zip_code_prefix',right_on='geolocation_zip_code_prefix', how='right')
OT

,customer_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,...,product_id,seller_id,shipping_limit_date,price,freight_value,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,05b005e82f3f2dcc41b5504f00484e50,1037.0,sao paulo,SP,e260cc3baa8f4aae3fab201ef60e1127,delivered,2018-08-17 10:59:04,2018-08-18 03:09:46,2018-08-20 13:43:00,2018-08-21 17:51:40,...,d7a023eecac412d29d49735e9e9b629f,2953ce3a88f5e3c3b696d77fc9e4c8eb,2018-08-21 03:09:46,25.00,8.34,1037,-23.545621,-46.639292,sao paulo,SP
1,19ee522d0dd140702062bb89e4820e19,1037.0,sao paulo,SP,14c7dfb8e61a3df193f153c72a99a3e5,delivered,2018-05-16 12:12:10,2018-05-16 12:39:24,2018-06-04 07:18:00,2018-06-05 20:07:46,...,e0d64dcfaa3b6db5c54ca298ae101d05,2eb70248d66e0e3ef83659f71b244378,2018-05-28 12:30:59,128.90,7.77,1037,-23.545621,-46.639292,sao paulo,SP
2,6519f59a7687a4661f7c8a7e24f28f94,1037.0,sao paulo,SP,d4daa9ee1fe28458773297759dbfe2bc,delivered,2018-05-08 11:15:05,2018-05-10 02:57:14,2018-05-11 19:00:00,2018-05-14 21:36:38,...,b2855c4e42b8a50f359904c6763eeddc,17a053fcb14bd219540cbde0df490be0,2018-05-17 02:57:14,369.90,35.36,1037,-23.545621,-46.639292,sao paulo,SP
3,6519f59a7687a4661f7c8a7e24f28f94,1037.0,sao paulo,SP,d4daa9ee1fe28458773297759dbfe2bc,delivered,2018-05-08 11:15:05,2018-05-10 02:57:14,2018-05-11 19:00:00,2018-05-14 21:36:38,...,b2855c4e42b8a50f359904c6763eeddc,17a053fcb14bd219540cbde0df490be0,2018-05-17 02:57:14,369.90,35.36,1037,-23.545621,-46.639292,sao paulo,SP
4,9a02295e3381803554347ab4dc1ab41b,1046.0,sao paulo,SP,60a7df16f9a8d8f38bd974b8a873167d,delivered,2018-07-26 01:27:57,2018-07-26 01:35:10,2018-07-26 15:16:00,2018-07-30 21:32:51,...,31b8e7c2a22f3dba5183cc110bdd72f7,7d13fca15225358621be4086e1eb0964,2018-08-06 01:35:10,185.00,13.96,1046,-23.546081,-46.644820,sao paulo,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17227979,11ec73ddb032be97ae8f0219cce6cfa3,99950.0,tapejara,RS,8729a8f7c27d03afe731463091711489,delivered,2016-10-05 17:16:17,2016-10-06 15:52:09,2016-10-30 14:02:20,2016-11-01 18:18:59,...,4e0946aebc8e1d7521219ec1e7380aed,817f85dbb65aa3e70831d90fe75cdf89,2016-10-21 16:22:50,128.90,23.22,99950,-28.070104,-52.018658,tapejara,RS
17227980,51293a462a75bbaa62b024a7da9e068a,99950.0,tapejara,RS,11210d2ba14b85282d66a4c956724533,delivered,2018-02-05 16:15:05,2018-02-06 04:33:00,2018-02-20 13:48:59,2018-03-06 11:29:04,...,516ccdc0667fe7e260156d1998ef9546,7c67e1448b00f6e969d365cea6b010ab,2018-02-20 02:55:41,116.94,34.18,99950,-28.070104,-52.018658,tapejara,RS
17227981,4e37f00d687d9dbb17009dea9767b1e6,99950.0,tapejara,RS,7b25b2356eef14019a831a9c9636c146,delivered,2017-08-12 23:12:48,2017-08-12 23:25:47,2017-08-15 19:26:45,2017-08-21 19:57:21,...,9165e7a5f9ef266f66ca19a816cdc657,48436dade18ac8b2bce089ec2a041202,2017-08-16 23:25:47,125.90,23.75,99950,-28.070104,-52.018658,tapejara,RS
17227982,cbc69ea8e3b1fdb3cbc421f7d3f72fc1,99950.0,tapejara,RS,4610355b7b9a4c4d4c176acaf273b7e2,delivered,2017-05-11 10:17:37,2017-05-11 10:25:23,2017-05-16 11:22:31,2017-05-24 08:37:41,...,a3ceb95649a48c0c54ae4bd1dd66d035,6c177e38df6d3f34182b1f1d427231bf,2017-05-22 10:25:23,130.00,15.66,99950,-28.070104,-52.018658,tapejara,RS
17227983,f8260ac0cb6df254a4c7ec7dd62a3aaa,99950.0,tapejara,RS,615774e695ab140dcb5e1c0aeb15b9cc,delivered,2018-02-26 09:32:34,2018-02-26 09:50:13,2018-03-09 22:21:16,2018-03-16 14:41:05,...,1a909e04ddbc64bda3fc905834678201,1c68394e931a64f90ea236c5ea590300,2018-03-08 09:50:13,76.90,15.29,99950,-28.070104,-52.018658,tapejara,RS

In [16]:
OT.drop_duplicates()

,customer_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,...,product_id,seller_id,shipping_limit_date,price,freight_value,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,05b005e82f3f2dcc41b5504f00484e50,1037.0,sao paulo,SP,e260cc3baa8f4aae3fab201ef60e1127,delivered,2018-08-17 10:59:04,2018-08-18 03:09:46,2018-08-20 13:43:00,2018-08-21 17:51:40,...,d7a023eecac412d29d49735e9e9b629f,2953ce3a88f5e3c3b696d77fc9e4c8eb,2018-08-21 03:09:46,25.00,8.34,1037,-23.545621,-46.639292,sao paulo,SP
1,19ee522d0dd140702062bb89e4820e19,1037.0,sao paulo,SP,14c7dfb8e61a3df193f153c72a99a3e5,delivered,2018-05-16 12:12:10,2018-05-16 12:39:24,2018-06-04 07:18:00,2018-06-05 20:07:46,...,e0d64dcfaa3b6db5c54ca298ae101d05,2eb70248d66e0e3ef83659f71b244378,2018-05-28 12:30:59,128.90,7.77,1037,-23.545621,-46.639292,sao paulo,SP
2,6519f59a7687a4661f7c8a7e24f28f94,1037.0,sao paulo,SP,d4daa9ee1fe28458773297759dbfe2bc,delivered,2018-05-08 11:15:05,2018-05-10 02:57:14,2018-05-11 19:00:00,2018-05-14 21:36:38,...,b2855c4e42b8a50f359904c6763eeddc,17a053fcb14bd219540cbde0df490be0,2018-05-17 02:57:14,369.90,35.36,1037,-23.545621,-46.639292,sao paulo,SP
3,6519f59a7687a4661f7c8a7e24f28f94,1037.0,sao paulo,SP,d4daa9ee1fe28458773297759dbfe2bc,delivered,2018-05-08 11:15:05,2018-05-10 02:57:14,2018-05-11 19:00:00,2018-05-14 21:36:38,...,b2855c4e42b8a50f359904c6763eeddc,17a053fcb14bd219540cbde0df490be0,2018-05-17 02:57:14,369.90,35.36,1037,-23.545621,-46.639292,sao paulo,SP
4,9a02295e3381803554347ab4dc1ab41b,1046.0,sao paulo,SP,60a7df16f9a8d8f38bd974b8a873167d,delivered,2018-07-26 01:27:57,2018-07-26 01:35:10,2018-07-26 15:16:00,2018-07-30 21:32:51,...,31b8e7c2a22f3dba5183cc110bdd72f7,7d13fca15225358621be4086e1eb0964,2018-08-06 01:35:10,185.00,13.96,1046,-23.546081,-46.644820,sao paulo,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17227953,cbc69ea8e3b1fdb3cbc421f7d3f72fc1,99950.0,tapejara,RS,4610355b7b9a4c4d4c176acaf273b7e2,delivered,2017-05-11 10:17:37,2017-05-11 10:25:23,2017-05-16 11:22:31,2017-05-24 08:37:41,...,a3ceb95649a48c0c54ae4bd1dd66d035,6c177e38df6d3f34182b1f1d427231bf,2017-05-22 10:25:23,130.00,15.66,99950,-28.068639,-52.010705,tapejara,RS
17227954,f8260ac0cb6df254a4c7ec7dd62a3aaa,99950.0,tapejara,RS,615774e695ab140dcb5e1c0aeb15b9cc,delivered,2018-02-26 09:32:34,2018-02-26 09:50:13,2018-03-09 22:21:16,2018-03-16 14:41:05,...,1a909e04ddbc64bda3fc905834678201,1c68394e931a64f90ea236c5ea590300,2018-03-08 09:50:13,76.90,15.29,99950,-28.068639,-52.010705,tapejara,RS
17227972,964b34423c822e9bd9831635ccc83db2,99980.0,david canabarro,RS,0bf144db6ca7ef970a25b6a720947622,delivered,2018-05-29 16:36:26,2018-05-29 16:51:39,2018-05-30 14:55:00,2018-06-12 16:18:30,...,ffb2e8c1ddc7c3e590d2bc4c91de53e1,39d61be7a92eb77b7da367bd4845bc0e,2018-06-06 16:51:39,48.99,19.32,99980,-28.388932,-51.846871,david canabarro,RS
17227973,964b34423c822e9bd9831635ccc83db2,99980.0,david canabarro,RS,0bf144db6ca7ef970a25b6a720947622,delivered,2018-05-29 16:36:26,2018-05-29 16:51:39,2018-05-30 14:55:00,2018-06-12 16:18:30,...,479d5974c7824b584a62c88885c957b4,39d61be7a92eb77b7da367bd4845bc0e,2018-06-06 16:51:39,48.99,19.32,99980,-28.388932,-51.846871,david canabarro,RS
17227974,657ba09c6edfbbc09f6054f541ec1f90,99980.0,david canabarro,RS,f551ed5f4c40a33b4922f6d2bd276941,delivered,2017-08-23 16:05:59,2017-08-23 16:28:57,2017-08-24 14:46:50,2017-09-11 20:13:33,...,777d2e438a1b645f3aec9bd57e92672c,4a3ca9315b744ce9f8e9374361493884,2017-08-29 16:28:57,69.90,16.25,99980,-28.388932,-51.846871,david canabarro,RS

In [17]:
OT.dropna()

,customer_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,...,product_id,seller_id,shipping_limit_date,price,freight_value,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,05b005e82f3f2dcc41b5504f00484e50,1037.0,sao paulo,SP,e260cc3baa8f4aae3fab201ef60e1127,delivered,2018-08-17 10:59:04,2018-08-18 03:09:46,2018-08-20 13:43:00,2018-08-21 17:51:40,...,d7a023eecac412d29d49735e9e9b629f,2953ce3a88f5e3c3b696d77fc9e4c8eb,2018-08-21 03:09:46,25.00,8.34,1037,-23.545621,-46.639292,sao paulo,SP
1,19ee522d0dd140702062bb89e4820e19,1037.0,sao paulo,SP,14c7dfb8e61a3df193f153c72a99a3e5,delivered,2018-05-16 12:12:10,2018-05-16 12:39:24,2018-06-04 07:18:00,2018-06-05 20:07:46,...,e0d64dcfaa3b6db5c54ca298ae101d05,2eb70248d66e0e3ef83659f71b244378,2018-05-28 12:30:59,128.90,7.77,1037,-23.545621,-46.639292,sao paulo,SP
2,6519f59a7687a4661f7c8a7e24f28f94,1037.0,sao paulo,SP,d4daa9ee1fe28458773297759dbfe2bc,delivered,2018-05-08 11:15:05,2018-05-10 02:57:14,2018-05-11 19:00:00,2018-05-14 21:36:38,...,b2855c4e42b8a50f359904c6763eeddc,17a053fcb14bd219540cbde0df490be0,2018-05-17 02:57:14,369.90,35.36,1037,-23.545621,-46.639292,sao paulo,SP
3,6519f59a7687a4661f7c8a7e24f28f94,1037.0,sao paulo,SP,d4daa9ee1fe28458773297759dbfe2bc,delivered,2018-05-08 11:15:05,2018-05-10 02:57:14,2018-05-11 19:00:00,2018-05-14 21:36:38,...,b2855c4e42b8a50f359904c6763eeddc,17a053fcb14bd219540cbde0df490be0,2018-05-17 02:57:14,369.90,35.36,1037,-23.545621,-46.639292,sao paulo,SP
4,9a02295e3381803554347ab4dc1ab41b,1046.0,sao paulo,SP,60a7df16f9a8d8f38bd974b8a873167d,delivered,2018-07-26 01:27:57,2018-07-26 01:35:10,2018-07-26 15:16:00,2018-07-30 21:32:51,...,31b8e7c2a22f3dba5183cc110bdd72f7,7d13fca15225358621be4086e1eb0964,2018-08-06 01:35:10,185.00,13.96,1046,-23.546081,-46.644820,sao paulo,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17227979,11ec73ddb032be97ae8f0219cce6cfa3,99950.0,tapejara,RS,8729a8f7c27d03afe731463091711489,delivered,2016-10-05 17:16:17,2016-10-06 15:52:09,2016-10-30 14:02:20,2016-11-01 18:18:59,...,4e0946aebc8e1d7521219ec1e7380aed,817f85dbb65aa3e70831d90fe75cdf89,2016-10-21 16:22:50,128.90,23.22,99950,-28.070104,-52.018658,tapejara,RS
17227980,51293a462a75bbaa62b024a7da9e068a,99950.0,tapejara,RS,11210d2ba14b85282d66a4c956724533,delivered,2018-02-05 16:15:05,2018-02-06 04:33:00,2018-02-20 13:48:59,2018-03-06 11:29:04,...,516ccdc0667fe7e260156d1998ef9546,7c67e1448b00f6e969d365cea6b010ab,2018-02-20 02:55:41,116.94,34.18,99950,-28.070104,-52.018658,tapejara,RS
17227981,4e37f00d687d9dbb17009dea9767b1e6,99950.0,tapejara,RS,7b25b2356eef14019a831a9c9636c146,delivered,2017-08-12 23:12:48,2017-08-12 23:25:47,2017-08-15 19:26:45,2017-08-21 19:57:21,...,9165e7a5f9ef266f66ca19a816cdc657,48436dade18ac8b2bce089ec2a041202,2017-08-16 23:25:47,125.90,23.75,99950,-28.070104,-52.018658,tapejara,RS
17227982,cbc69ea8e3b1fdb3cbc421f7d3f72fc1,99950.0,tapejara,RS,4610355b7b9a4c4d4c176acaf273b7e2,delivered,2017-05-11 10:17:37,2017-05-11 10:25:23,2017-05-16 11:22:31,2017-05-24 08:37:41,...,a3ceb95649a48c0c54ae4bd1dd66d035,6c177e38df6d3f34182b1f1d427231bf,2017-05-22 10:25:23,130.00,15.66,99950,-28.070104,-52.018658,tapejara,RS
17227983,f8260ac0cb6df254a4c7ec7dd62a3aaa,99950.0,tapejara,RS,615774e695ab140dcb5e1c0aeb15b9cc,delivered,2018-02-26 09:32:34,2018-02-26 09:50:13,2018-03-09 22:21:16,2018-03-16 14:41:05,...,1a909e04ddbc64bda3fc905834678201,1c68394e931a64f90ea236c5ea590300,2018-03-08 09:50:13,76.90,15.29,99950,-28.070104,-52.018658,tapejara,RS

In [18]:
O

,customer_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00,1,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,2017-05-22 15:22:12,124.99,21.88
1,18955e83d337fd6b2def6b18a428ac77,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06 00:00:00,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-01-18 20:58:32,289.00,46.48
2,4e7b3e00288586ebd08712fdd0374a03,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13 00:00:00,1,bd07b66896d6f1494f5b86251848ced7,7c67e1448b00f6e969d365cea6b010ab,2018-06-05 16:19:10,139.94,17.79
3,b2b6027bc5c5109e529d4dc6358b12c3,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10 00:00:00,1,a5647c44af977b148e0a3a4751a09e2e,7c67e1448b00f6e969d365cea6b010ab,2018-03-27 16:31:16,149.94,23.36
4,4f2d8ab171c80ec8364f7c12e35b23ad,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15 00:00:00,1,9391a573abe00141c56e38d84d7d5b3b,4a3ca9315b744ce9f8e9374361493884,2018-07-31 10:10:09,230.00,22.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,17ddf5dd5d51696bb3d7c6291687be6f,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,2018-04-13 20:06:37,2018-04-25 00:00:00,1,ccb4503d9d43d245d3b295d0544f988b,527801b552d0077ffd170872eb49683b,2018-04-12 16:08:45,74.90,13.88
112646,e7b71a9017aa05c9a7fd292d714858e8,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,2018-04-11 18:54:45,2018-04-20 00:00:00,1,9ede6b0570a75a4b9de4f383329f99ee,3fd1e727ba94cfe122d165e176ce7967,2018-04-10 08:35:12,114.90,14.16
112647,5e28dfe12db7fb50a4b2f691faecea5e,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,2018-05-09 19:03:15,2018-05-02 00:00:00,1,7a5d2e1e131a860ae7d18f6fffa9d689,d9e7e7778b32987280a6f2cb9a39c57d,2018-04-12 20:30:03,37.00,19.04
112648,56b18e2166679b8a959d72dd06da27f9,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,2017-11-16 19:58:39,2017-12-05 00:00:00,1,f819f0c84a64f02d3a5606ca95edd272,4869f7a5dfa277a7dca6462dcf3b52b2,2017-11-09 21:15:51,689.00,22.07
112649,274fa6071e5e17fe303b9748641082c8,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,2017-12-19 18:50:39,2017-12-21 19:17:21,2017-12-26 18:42:36,2018-01-08 00:00:00,1,017692475c1c954ff597feda05131d73,3c7c4a49ec3c6550809089c6a2ca9370,2017-12-26 18:50:39,13.99,7.78

In [22]:
O.dtypes

customer_id                              object
customer_zip_code_prefix                  int64
customer_city                            object
customer_state                           object
order_id                                 object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date             object
order_delivered_customer_date            object
order_estimated_delivery_date            object
order_item_id                             int64
product_id                               object
seller_id                                object
shipping_limit_date                      object
price                                   float64
freight_value                           float64
dtype: object

In [20]:
O['order_approved_at'] = pd.to_datetime(O['order_approved_at'])

In [21]:
O['order_purchase_timestamp'] = pd.to_datetime(O['order_purchase_timestamp'])

In [23]:
O['order_delivered_carrier_date'] = pd.to_datetime(O['order_delivered_carrier_date'])

In [24]:
O['order_delivered_customer_date'] = pd.to_datetime(O['order_delivered_customer_date'])

In [25]:
O['order_estimated_delivery_date'] = pd.to_datetime(O['order_estimated_delivery_date'])

In [26]:
O['shipping_limit_date'] = pd.to_datetime(O['shipping_limit_date'])

In [27]:
O['Date_Arrived'] = O['order_delivered_customer_date'] - O['order_approved_at']

In [29]:
O['Date_Estimated'] = O['order_estimated_delivery_date'] - O['order_approved_at']

In [30]:
O

,customer_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,Date_Arrived,Date_Estimated
0,06b8999e2fba1a1fbc88172c00ba8bc7,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05,1,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,2017-05-22 15:22:12,124.99,21.88,8 days 19:13:23,19 days 08:37:48
1,18955e83d337fd6b2def6b18a428ac77,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-01-18 20:58:32,289.00,46.48,16 days 15:42:47,24 days 03:01:28
2,4e7b3e00288586ebd08712fdd0374a03,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13,1,bd07b66896d6f1494f5b86251848ced7,7c67e1448b00f6e969d365cea6b010ab,2018-06-05 16:19:10,139.94,17.79,25 days 01:39:41,23 days 07:40:50
3,b2b6027bc5c5109e529d4dc6358b12c3,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10,1,a5647c44af977b148e0a3a4751a09e2e,7c67e1448b00f6e969d365cea6b010ab,2018-03-27 16:31:16,149.94,23.36,14 days 22:35:06,27 days 06:30:41
4,4f2d8ab171c80ec8364f7c12e35b23ad,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15,1,9391a573abe00141c56e38d84d7d5b3b,4a3ca9315b744ce9f8e9374361493884,2018-07-31 10:10:09,230.00,22.25,11 days 10:45:39,16 days 13:49:51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,17ddf5dd5d51696bb3d7c6291687be6f,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,2018-04-13 20:06:37,2018-04-25,1,ccb4503d9d43d245d3b295d0544f988b,527801b552d0077ffd170872eb49683b,2018-04-12 16:08:45,74.90,13.88,6 days 03:57:52,17 days 07:51:15
112646,e7b71a9017aa05c9a7fd292d714858e8,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,2018-04-11 18:54:45,2018-04-20,1,9ede6b0570a75a4b9de4f383329f99ee,3fd1e727ba94cfe122d165e176ce7967,2018-04-10 08:35:12,114.90,14.16,7 days 10:19:33,15 days 15:24:48
112647,5e28dfe12db7fb50a4b2f691faecea5e,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,2018-05-09 19:03:15,2018-05-02,1,7a5d2e1e131a860ae7d18f6fffa9d689,d9e7e7778b32987280a6f2cb9a39c57d,2018-04-12 20:30:03,37.00,19.04,30 days 22:33:12,23 days 03:29:57
112648,56b18e2166679b8a959d72dd06da27f9,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,2017-11-16 19:58:39,2017-12-05,1,f819f0c84a64f02d3a5606ca95edd272,4869f7a5dfa277a7dca6462dcf3b52b2,2017-11-09 21:15:51,689.00,22.07,12 days 22:27:19,31 days 02:28:40
112649,274fa6071e5e17fe303b9748641082c8,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,2017-12-19 18:50:39,2017-12-21 19:17:21,2017-12-26 18:42:36,2018-01-08,1,017692475c1c954ff597feda05131d73,3c7c4a49ec3c6550809089c6a2ca9370,2017-12-26 18:50:39,13.99,7.78,6 days 23:51:57,19 days 05:09:21